site_name: Sloth Framework
copyright: Copyright &copy; 2022 maintained by mayu
repo_url: https://git.zuoyebang.cc/inno_newhw_test/sloth
repo_name: inno_newhw_test/sloth

# The material theme settings
theme:
  name: material
  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/gitlab

  features:
    - navigation.tabs
    - navigation.instant
    - announce.dismissÎ
    - navigation.tracking
    - toc.integrate
    - navigation.top

plugins:
  - search
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# The site navigation
nav:
  - Home: index.md
  - Intro: intro/intro.md
  - VSCode: vscode.md
