site_name: Sloth Framework
site_dir: public
site_url: http://mayu08.gitpages.zuoyebang.cc/sloth-doc

copyright: Copyright &copy; 2022 maintained by MaYu

# The material theme settings
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/gitlab

  features:
    - navigation.tabs
    - navigation.instant
    - announce.dismissÎ
    - navigation.tracking
    - toc.integrate
    - navigation.top
    - content.code.annotate

plugins:
  - search
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# The site navigation
nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started/installation.md
      - Project structure: getting-started/project-structure.md
      - The first case: getting-started/the-first-case.md
      - Report: getting-started/report.md
  - Guide:
      - Element locating: guide/element-locating.md
      - Task executor: guide/task-executor.md
      - Working with multiple devices: guide/working-with-multiple-devices.md
      - Voice engine: guide/voice-engine.md
